### ISSUE TITLE
merging python3

### ISSUE THREAD

**Issue by looooo** [looooo/FreeCAD#8]
## Mod
- [x] Arch [needs again some love]
- [x] Cam [no diff]
- [x] Complete
- [x] Draft
- [x] Drawing (seems to be dead)
- [x] __Fem__ [PR]
- [x] Idf [no diff]
- [x] Image
- [x] Import
- [x] Inspection
- [x] JtReader (dead?) [no diff]
- [x] Material
- [x] Measure
- [x] Mesh
- [x] MeshPart
- [x] OpenSCAD
- [x] __Part__ 
- [x] __Part-Design__ 
- [x] __Path__ [runtime problems]
- [x] Plot [no diff]
- [x] Points
- [x] Raytracing
- [x] ReverseEngeneering
- [x] Robot
- [x] Sandbox
- [x] Ship [no diff]
- [x] Show [no diff]
- [x] __Sketcher__ 
- [x] __Spreadsheet__
- [x] __Start__
- [x] TemplatePyMod
- [x] __Test__ 
- [x] __TechDraw__
- [x] Web 

## FreeCAD
- [x] __cmakeList.txt__
- [x] __Tools__
  - [x] 1. Part
  - [x] 2. Part
  - [x] generate.py
  - [x] generateTemplates/templateClassPyExport.py
- [x] __Base__
  - [x] files A-I
  - [x] files I-R
  - [x] files R-Z
  - [x] PyObjectBase.h
  - [x] PyObjectBase.cpp
- [x] __App__
  - [x] files A-C
  - [x] files D-Z
  - [x] ExtensionContainer.cpp
  - [x] FeaturePythonPyImp.h
  - [x] FeaturePythonPyImp.inl
- [x] __Gui__
  - [x] files A-P
  - [x] files P-Z
- [x] cmake/... [ ] 
- [x] src/salomesmesh
- [x] Main

... to be continued

**Comment by joha2** [comment]
Hi lo, sorry for my long absence. I wish you a happy new year. Did you enjoy new years eve? Why do you do all this stuff with python3? Is FC for version 0.17 to be ported to python3? I thought the porting is still at the very beginning and there were some issues with the C++ interfacess? Best wishes, Johannes

**Comment by kkremitzki** [comment]
The Start WB needs attention as well. If you can open a Python 3 compile, load Start and try to open an example, for example. I can look at that, can you add it to checklist?

**Comment by looooo** [comment]
@joha2 thanks, for the wishes. Hope you had a good time as well. I joined the python3 effort, because I didn't came any further with the fenics-solver. But now I am stuck with python3 port, so maybe it's a good time to change project-priority again ;-)
There are still many things to do. But I have the feeling it could be possible to get a usable python3-version soon.
@kkremitzki thanks for the hint. I simple forgot the start workbench, and I can confirm the problem with loading files (name 'execfile' is not defined)

**Comment by flutefreak7** [comment]
Just stumbled in on this and thought I'd google the most recent thing you mentionted... execfile is a fairly straightforward one to update (http://stackoverflow.com/a/437857/1639671):

    with open("somefile.py") as f:
        code = compile(f.read(), "somefile.py", 'exec')
        exec(code, global_vars, local_vars)

or there's another more concise solution using python 3's 'runpy' module: http://stackoverflow.com/a/24261031/1639671.  If there are useful local/global variables in the current namespace at the time of executing the file, that namespace would need to be passed to the runpy.run_path() I believe.

**Comment by flutefreak7** [comment]
I currently know nothing about FreeCAD (that could change... I'm interested...) but a fair amount about Python and may can help get Python 2 code working in Python 3.  I'm at least following this thread now and will be happy to help run down future translation issues.  I would love FreeCAD to be up to date with current 64-bit Python 3.  Also what version of Python 3 are you targeting?  Changes made in python's compilation on Windows in 3.5 could create unique issues for 3.4 vs. 3.5+ that I know the PySide2 & PyQt5 folks have had to deal with.

**Comment by luzpaz** [comment]
what about 
- [ ] Cam WB ?

**Comment by looooo** [comment]
> Just stumbled in on this and thought I'd google the most recent thing you mentionted... execfile is a fairly straightforward one to update (http://stackoverflow.com/a/437857/1639671):

The problem with exec was, that the exec function and the exec keyword didn't behave the same in python2. There were differences in python2.7.x and python2.7.y version. While the exec function worked the same in python2.7.x, it failed on python2.7.y. As the exec keyword can't be used in a try block in python3, I put the python2 and python3 relevant code in different files. This is maybe a very dirty solution, but it works. :-)
If you want you can try to find a better solution. The relevant code can be found [here](https://github.com/looooo/FreeCAD/blob/py3-21/src/Tools/generateBase/generateTools.py#L10L21). Feel free to experiment with that.

> I currently know nothing about FreeCAD (that could change... I'm interested...) but a fair amount about Python and may can help get Python 2 code working in Python 3.

That is good to know. If you want to help, you can look at python code in all the merged (ticked) modules. There are still many python3 problems which haven't been ported.

>  Also what version of Python 3 are you targeting? Changes made in python's compilation on Windows in 3.5 could create unique issues for 3.4 vs. 3.5+ that I know the PySide2 & PyQt5 folks have had to deal with.

We are only using python3.5 right now. After the merge we can try to get everything python3.6 ready but python3.4 will not be supported.
Currently I am using conda to test the python3 branch on linux. We had a discussion to also make FreeCAD with python3 available via conda on windows. But I think there are still some hurdles to take. 

Regarding PySide2: There is an ongoing effort to port FreeCAD to qt5 and PySide2. [eg topic in forum](https://forum.freecadweb.org/viewtopic.php?f=10&t=13710). I think there is also help appreciated. Just in case you want to share your PySide2 knowledge :-)

**Comment by looooo** [comment]
> what about    Cam WB ?
thanks, added.

**Comment by luzpaz** [comment]
@looooo are you planning to hit Tools/,  Base/, and App/?

**Comment by looooo** [comment]
yes I think so. But it maybe needs more time... Some changes are also python2 relevant, and could break things... So testing of the py3-branch with python2 will be necessary too. Currently my time is a bit limited... Also I wait for https://github.com/FreeCAD/FreeCAD/pull/602 to be included...

**Comment by luzpaz** [comment]
Thanks @looooo btw... I've been working on attaching all the py3 commits to the mantis bug 995. You can see it in the ticket https://freecadweb.org/tracker/view.php?id=995 I've added a mention in your above PR on how to do that.  Thanks for all your work!

**Comment by looooo** [comment]
sry for my ignorance. It's quite nice to see the commits within the bugreport. PR's are updated.

**Comment by luzpaz** [comment]
@looooo no worries ;)
Btw I meant from here on out, no need to do so with previous commits.
Also the above trigger can't be added to the github conversation, it needs to be in the git commit message, that is what the bugtracker reads. For example this recent commit you made would only register if you re-pushed it with a modified commit message BUT there is no need for that. I can add it on the mantis side of things. So again this just applies to commits you will make in the future. Cheers!

**Comment by looooo** [comment]
I think we can close this issue  : )
